### ISSUE TITLE
【Sauce】考勤

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#13]
可以查到考勤情况吗？？

---
**用户信息**
用户名：Sauce（何锡瑶-2015211426）
手机型号：MI NOTE LTE
操作系统：Android 6.0.1（android - 392x630）
微信版本号：6.5.7
小程序版本号：v1.0.0
基础库版本：1.1.1

**Comment by NullYing** [comment]
暂时没有，需要学校提供接口
