### ISSUE TITLE
【娜娜^o^】登录不了

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#15]
密码总是说不对，无法绑定

---
**用户信息**
用户名：娜娜^o^（郑燕娜-2016153133）
手机型号：OPPO R9m
操作系统：Android 5.1（android - 360x574）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5

**Comment by NullYing** [comment]
你不是已经绑定了？
