### ISSUE TITLE
【Flash.】校园卡绑定失败

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#16]
显示：连接超时。每次都如此

---
**用户信息**
用户名：Flash.（费嘉熠-2014143220）
手机型号：R7Plus
操作系统：Android 5.0（android - 360x527）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5

**Comment by NullYing** [comment]
因为周末校园卡服务器有时候会关闭，所以绑定不了
