### ISSUE TITLE
【ฅ●ω●ฅ🌀SinYuuuu❌まゆゆ】成绩查询

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#17]
查询出来的成绩是上学期的……

---
**用户信息**
用户名：ฅ●ω●ฅ🌀SinYuuuu❌まゆゆ（梁倩瑜-2015151241）
手机型号：iPhone SE<iPhone8,4>
操作系统：iOS 10.3.1（ios - 320x504）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5

**Comment by NullYing** [comment]
这并不是bug哈
