### ISSUE TITLE
【部部】查不了我平时分

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#20]
查不了我平时分

---
**用户信息**
用户名：部部（莫茵-2015112121）
手机型号：A51
操作系统：Android 5.1.1（android - 360x567）
微信版本号：6.5.3
小程序版本号：v1.0.1
基础库版本：undefined

**Comment by NullYing** [comment]
可以的哈，请升级下你的微信

**Comment by NullYing** [comment]
请升级微信
