### ISSUE TITLE
【彼  此  不分】无法绑定校园卡

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#21]
在饭堂滴饭卡要密码时身份证后六位都对，但在绑定小喵时输入密码是身份证后六位却提示用户名或密码错误，我的用户名是学号，这个是没错的。麻烦解决问题。

---
**用户信息**
用户名：彼  此  不分（何裕俊-2016130226）
手机型号：SCL-AL00
操作系统：Android 5.1.1（android - 360x519）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5

**Comment by NullYing** [comment]
错了，用户名是身份证号
