### ISSUE TITLE
【Scrooge and Goatherd】查询成绩

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#22]
查询成绩看着那本书翻了半天都没显示出来

---
**用户信息**
用户名：Scrooge and Goatherd（廖少枫-2015131837）
手机型号：m2 note
操作系统：Android 5.1（android - 360x570）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
请升级微信
