### ISSUE TITLE
【❌】不能查询成绩

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#24]
不能查询成绩 也不能切换账号

---
**用户信息**
用户名：❌（冯永杰-2015122824）
手机型号：iPhone 5s (GSM+CDMA)<iPhone6,2>
操作系统：iOS 8.3（ios - 320x504）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
升级微信
