### ISSUE TITLE
【24K纯滑稽】查不到成绩

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#25]
一直加载

---
**用户信息**
用户名：24K纯滑稽（刘湘悦-2015145328）
手机型号：Redmi Note 3
操作系统：Android 6.0.1（android - 360x572）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
版本不兼容，请升级微信，bug已被发现
