### ISSUE TITLE
【_(:з_Kang】成绩查询点开没后序了。。

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#26]
一直都是这图的状态

---
**用户信息**
用户名：_(:з_Kang（杨权康-2016131836）
手机型号：m3 note
操作系统：Android 5.1（android - 360x570）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

![img](http://qn.gxgk.cc/issues_1499057784?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
请升级微信
