### ISSUE TITLE
【MaHa】成绩查询

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#27]
不能查询成绩，但其它功能都可以使用

---
**用户信息**
用户名：MaHa（韩楚玲-2015112945）
手机型号：vivo X5Pro V
操作系统：Android 5.0.2（android - 360x569）
微信版本号：6.5.6
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
升级微信
