### ISSUE TITLE
【翰海家】成绩查询

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#29]
为什么我查不了成绩？成绩出来得很慢。

---
**用户信息**
用户名：翰海家（李东翰-2016124204）
手机型号：GT-I9060
操作系统：Android 4.2.2（android - 320x460）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
请升级微信
