### ISSUE TITLE
【S•mark】平时成绩查不了！

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#30]
我都不知道为什么 一直卡死在成绩查询

---
**用户信息**
用户名：S•mark（赖景辉-2015131923）
手机型号：vivo Xplay3S
操作系统：Android 4.3（android - 360x572）
微信版本号：6.5.4
小程序版本号：v1.0.1
基础库版本：1.0.1

**Comment by NullYing** [comment]
请升级微信
