### ISSUE TITLE
【张淑婷张大帅 】图书借阅情况

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#36]
可以展现大学期间借过几本书 借了什么书吗

---
**用户信息**
用户名：张淑婷张大帅 （张淑婷-2015122752）
手机型号：OPPO A59s
操作系统：Android 5.1（android - 360x574）
微信版本号：6.5.10
小程序版本号：v1.0.1
基础库版本：1.4.4

**Comment by NullYing** [comment]
可以

**Comment by NullYing** [comment]
后端已经开发完成，前端没接上

**Comment by NullYing** [comment]
已上线
