### ISSUE TITLE
【undefined】很无奈

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#37]
已经更改了帐号但是查询的成绩还是上一个帐号的成绩！！！取关再关注也没有用！很绝望！图片是我的帐号 成绩是上一个帐号的

---
**用户信息**
用户名：undefined（方文正-2016143126）
手机型号：iPhone 6s<iPhone8,1>
操作系统：iOS 9.3.3（ios - 375x667）
微信版本号：6.5.7
小程序版本号：v1.0.1
基础库版本：1.1.1
网络类型：wifi

![img](http://qn.gxgk.cc/issues_1501988339?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
成绩大概会缓存10天左右

**Comment by NullYing** [comment]
已修复，重新绑定会删除缓存
