### ISSUE TITLE
【undefined】还是不行

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#39]
。。

---
**用户信息**
用户名：undefined（邓玉婷-2015144114）
手机型号：MI 6
操作系统：Android 7.1.1（android - 360x640）
微信版本号：6.5.10
小程序版本号：v1.0.1
基础库版本：1.4.4
网络类型：4g

![img](http://qn.gxgk.cc/issues_1502216997?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
寒假图书馆是关闭的
