### ISSUE TITLE
【undefined】问题

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#40]
绑定的饭卡不是我的。

---
**用户信息**
用户名：undefined（吴静仪-2016121421）
手机型号：Coolpad Y91-921
操作系统：Android 5.1.1（android - 360x640）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5
网络类型：wifi

**Comment by NullYing** [comment]
已经帮你清掉了
