### ISSUE TITLE
【undefined】课表加入上课时间

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#41]
如题

---
**用户信息**
用户名：undefined（叶焕新-2016131915）
手机型号：vivo X710F
操作系统：Android 4.4.2（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.1
基础库版本：1.5.3
网络类型：wifi

**Comment by NullYing** [comment]
课表上有上课时间了
