### ISSUE TITLE
【undefined】课程表排版错误

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#42]
广科小喵小程序的课程表排版有问题

---
**用户信息**
用户名：undefined（苏治桦-2015131413）
手机型号：iPhone 5s (GSM+CDMA)<iPhone6,2>
操作系统：iOS 8.2（ios - 320x568）
微信版本号：6.5.15
小程序版本号：v1.0.1
基础库版本：1.5.3
网络类型：wifi

![img](http://qn.gxgk.cc/issues_1504165559?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
我在我室友的苹果5s测试是没问题的，没办法触发bug也没办法修
