### ISSUE TITLE
【undefined】图书证无法绑定？

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#43]
为什么绑定不了图书证，绑定后要完善信息，又跳回到绑定页面

---
**用户信息**
用户名：undefined（罗杜-2015112917）
手机型号：PRA-AL00
操作系统：Android 7.0（android - 360x604）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5
网络类型：wifi

**Comment by NullYing** [comment]
已修复
