### ISSUE TITLE
【undefined】关于借阅功能

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#44]
一直显示登录界面，登录成功后还是登录界面，无法进入理想界面

---
**用户信息**
用户名：undefined（劳元源-2015131316）
手机型号：PRO 6s
操作系统：Android 6.0（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.1
基础库版本：1.5.3
网络类型：4g

**Comment by NullYing** [comment]
已修复
