### ISSUE TITLE
【undefined】课程显示不全，不可以自行添加课程，需要在人性化，方便一点

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#45]
课程显示不全，不可以自行添加课程，需要在人性化，方便一点

---
**用户信息**
用户名：undefined（吴静仪-2014113434）
手机型号：PLK-TL01H
操作系统：Android 6.0（android - 360x604）
微信版本号：6.5.10
小程序版本号：v1.0.1
基础库版本：1.4.4
网络类型：4g

**Comment by NullYing** [comment]
暂时没有该功能的开发计划，老油条准备毕业了
