### ISSUE TITLE
【undefined】校园卡绑定不了

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#46]
为什么我身份证后面是x就绑定不了校园卡？或者怎么绑？

---
**用户信息**
用户名：undefined（黄金铭-2016132109）
手机型号：m3 note
操作系统：Android 5.1（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.1
基础库版本：1.5.3
网络类型：4g

![img](http://qn.gxgk.cc/issues_1504501134?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
已解决
