### ISSUE TITLE
【undefined】错误

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#47]
空教室不正确，还没有更新

---
**用户信息**
用户名：undefined（林奕-2014121133）
手机型号：iPhone 5s (GSM+CDMA)<iPhone6,2>
操作系统：iOS 10.1（ios - 320x568）
微信版本号：6.5.8
小程序版本号：v1.0.1
基础库版本：1.2.5
网络类型：4g

**Comment by NullYing** [comment]
已经更新
