### ISSUE TITLE
【老牛】班级不对

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#48]
物流重新分班

---
**用户信息**
用户名：老牛（黄锐棚-2016113323）
手机型号：Redmi 4X
操作系统：Android 6.0.1（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.3
基础库版本：1.5.3
网络类型：wifi

**Comment by NullYing** [comment]
你看看教务系统你的班级改了？可以试下重新绑定
