### ISSUE TITLE
【Manuka】课表错误

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#49]
课表错了老子没有日语课

---
**用户信息**
用户名：Manuka（刘清桦-2016114343）
手机型号：MHA-AL00
操作系统：Android 7.0（android - 360x604）
微信版本号：6.5.13
小程序版本号：v1.0.3
基础库版本：1.5.3
网络类型：4g

![img](http://qn.gxgk.cc/issues_1505695088?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
由于教务系统原因，现在调整小程序为班级课表，公众号为个人课表
