### ISSUE TITLE
【CN_Luthus】课表没有公选课

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#52]
课表里没有公选课是为啥 教务系统的都有

---
**用户信息**
用户名：CN_Luthus（范仲军-2014131321）
手机型号：MI 5
操作系统：Android 7.0（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.3
基础库版本：1.5.3
网络类型：4g

**Comment by NullYing** [comment]
应该有了把
