### ISSUE TITLE
【无名sr】修改

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#55]
建议课表处加入时间

---
**用户信息**
用户名：无名sr（薛泽林-2017147433）
手机型号：MHA-AL00
操作系统：Android 7.0（android - 360x604）
微信版本号：6.5.16
小程序版本号：v1.0.3
基础库版本：1.6.0
网络类型：4g

**Comment by NullYing** [comment]
有点麻烦
