### ISSUE TITLE
【BIBI】课程表时间

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#56]
课程表的周数和实际周数不符合但是调不了？Ծ‸Ծ

---
**用户信息**
用户名：BIBI（刘碧晖-2015113346）
手机型号：MI 5
操作系统：Android 6.0（android - 360x640）
微信版本号：6.5.13
小程序版本号：v1.0.3
基础库版本：1.5.6
网络类型：wifi

![img](http://qn.gxgk.cc/issues_1508672558?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
现在还会？
