### ISSUE TITLE
【绫小路】查不到我的课表

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#58]
显示连接超时，而别的同学能查到QAQ

---
**用户信息**
用户名：绫小路（叶宏伟-2017131415）
手机型号：vivo X9
操作系统：Android 7.1.1（android - 360x640）
微信版本号：6.5.16
小程序版本号：v1.0.3
基础库版本：1.6.4
网络类型：4g

**Comment by NullYing** [comment]
已经修复
