### ISSUE TITLE
反馈时个人隐私问题

### ISSUE THREAD

**Issue by xiaoliuhao** [gxgk/gxgk-wechat-app#60]
之前为了方便定位问题，直接将用户的个人信息贴了出来，后来有用同学觉得反馈时连学号和姓名啥的都展示出来了有点不太好。修改之后同时也建议一下

**Comment by NullYing** [comment]
因为后台是没存任何反馈信息的，所以之前方便定位就贴了出来，你可以提一个pull request，删一下个人信息显示。

**Comment by NullYing** [comment]
刚刚没看到你是重邮的，😂😂😂我找个学弟修改下，我已经在实习了

**Comment by xiaoliuhao** [comment]
哈哈 我也是， 最近准备毕设题目又看了一下，准备过年删库跑路回学校

**Comment by NullYing** [comment]
已阉割了反馈功能，有师弟补上的话，我会让他留意这个功能
