### ISSUE TITLE
【Hhao】查不了成绩

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#61]
人家都可以打开查成绩 就我打不开？什么意思你们

---
**用户信息**
用户名：Hhao（李豪-2016123640）
手机型号：MI 5X
操作系统：Android 7.1.2（android - 360x640）
微信版本号：6.6.1
小程序版本号：v1.0.3
基础库版本：1.9.5
网络类型：4g

**Comment by NullYing** [comment]
教务系统原因，不做解释
