### ISSUE TITLE
【Xf】教务系统忘记密码

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#63]
教务系统忘记密码怎么办

---
**用户信息**
用户名：Xf（肖帆-2015123320）
手机型号：MHA-AL00
操作系统：Android 8.0.0（android - 360x602）
微信版本号：6.6.1
小程序版本号：v1.0.3
基础库版本：1.9.5
网络类型：4g

**Comment by NullYing** [comment]
找辅导员找回
