### ISSUE TITLE
【你头顶有摄像头】系别错误问题

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#64]
2017年广东科技学院将“应用英语系”更名为“外语系”
so
这边也能更改一下吗_(´ཀ`」 ∠)_日语本科学生看到自己被分为英语系心情也是蛮复杂的

---
**用户信息**
用户名：你头顶有摄像头（李雅雯-2017154125）
手机型号：iPhone 7<iPhone9,1>
操作系统：iOS 11.2.2（ios - 375x667）
微信版本号：6.6.1
小程序版本号：v1.0.3
基础库版本：1.9.5
网络类型：wifi

**Comment by NullYing** [comment]
因为教务系统长期没改。。。所以对应出错
