### ISSUE TITLE
【🌼】没新课表

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#67]
找不到新课表，只有上个学期的

---
**用户信息**
用户名：🌼（程思燕-2016122302）
手机型号：MI 5
操作系统：Android 7.0（android - 360x640）
微信版本号：6.6.1
小程序版本号：v1.0.3
基础库版本：1.9.9
网络类型：4g

![img](http://qn.gxgk.cc/issues_1518421664?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/6I6e6aaZ5bCP5Za1/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by NullYing** [comment]
由于各种原因，新课表优先在校园小萌提供，小萌课表功能由广科小喵提供。
