### ISSUE TITLE
【凉白开】转系了

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#68]
我已转到17级金工2

---
**用户信息**
用户名：凉白开（李卓俊-2017141150）
手机型号：OPPO R9 Plusm A
操作系统：Android 5.1.1（android - 360x640）
微信版本号：6.6.3
小程序版本号：v1.0.3
基础库版本：1.9.91
网络类型：4g

**Comment by NullYing** [comment]
重新绑定才会获取新信息，前提是教务系统已经改了
