### ISSUE TITLE
【阿姆斯特朗朗】校园卡查不了余额

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#69]
如题😬

---
**用户信息**
用户名：阿姆斯特朗朗（张虹羽-2016123504）
手机型号：iPhone 6 Plus<iPhone7,1>
操作系统：iOS 11.0.3（ios - 414x736）
微信版本号：6.6.3
小程序版本号：v1.0.3
基础库版本：1.9.91
网络类型：4g

**Comment by NullYing** [comment]
已经修复，该功能可能将会下线
