### ISSUE TITLE
【SUN C】课表报错

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#71]
课表课程有更改

---
**用户信息**
用户名：SUN C（陈阳-2017147338）
手机型号：MI 6
操作系统：Android 7.1.1（android - 360x640）
微信版本号：6.6.5
小程序版本号：v1.0.3
基础库版本：1.9.91
网络类型：4g

**Comment by NullYing** [comment]
请描述下改了什么，方便定位问题
