### ISSUE TITLE
【Adam_Lin】补考

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#74]
没有补考成绩

---
**用户信息**
用户名：Adam_Lin（林圣彬-2017131219）
手机型号：m1 metal
操作系统：Android 5.1（android - 360x640）
微信版本号：6.6.3
小程序版本号：v1.0.3
基础库版本：1.9.97
网络类型：4g

**Comment by NullYing** [comment]
请到公众号查询
