### ISSUE TITLE
【莞香小喵】关于后台接口文档的一些问题

### ISSUE THREAD

**Issue by NullYing** [gxgk/gxgk-wechat-app#78]
跟[We重邮](https://github.com/mcc108/wecqupt/issues/466)情况类似，学校接口带有隐私数据。因为等等特殊原因，我们无法开源。

有需要的同学可以通过微信扫一扫下面二维码来加入小密圈（知识星球），获取后台相关的信息文档，有提问的话我们也会在里面尽所能回答：

涵盖内容：广科小喵公众号，广科情报局，广科校园导览，莞香小喵，莞香客户端，校喵APP等等一系列莞香广科作品

![image](https://user-images.githubusercontent.com/10618381/40058111-c0983958-5882-11e8-9b21-1eb1dc565cda.png)

**Comment by skyoct** [comment]
您好，已经加入知识星球，请问文档哪里下载

**Comment by NullYing** [comment]
@skykiss 已经发表在知识星球里面

**Comment by NullYing** [comment]
emmmm,没精力维护，请勿加入
