### ISSUE TITLE
【Seven】校园卡

### ISSUE THREAD

**Issue by gxgk-admin** [gxgk/gxgk-wechat-app#82]
校园卡充值什么时候能好
天天都充不了😓 

---
**用户信息**
用户名：Seven（周嘉琪-2016112210）
手机型号：OPPO R11
操作系统：Android 7.1.1（android - 360x640）
微信版本号：6.6.5
小程序版本号：v1.0.3
基础库版本：1.9.97
网络类型：4g

**Comment by NullYing** [comment]
已联系学校处理
