### ISSUE TITLE
关于课表json数据

### ISSUE THREAD

**Issue by onionnet606** [gxgk/gxgk-wechat-app#88]
您好！我在开发过程中发现没有课表模拟json...
看的头疼，能否提供一下模拟的Json数据呢？十分感谢！

**Comment by ShadowWaIker** [comment]
之前有人提过这个issue的

https://github.com/gxgk/gxgk-wechat-app/issues/78

**Comment by onionnet606** [comment]
不是说没精力维护了吗…我只需要一个课表的json 不知道方便给吗…

**Comment by ShadowWaIker** [comment]
2333，我也不是这个项目的成员..
不过我一直在follow这个项目，这个一直都在更新，好像没有不维护的样子啊。可能是说知识星球没精力维护了吧。
我的仓库里面有个跟这个项目一样的从we重邮fork出来的校园助手的项目，你看看那个里面的课表（因为不知道we重邮返回的数据结构，所以课表模块我自己修改了）符合你的需求不，符合的话你可以把那个课表扒下来，我给你提供json数据。XD

**Comment by dairoot** [comment]
@ShadowWaIker @onionnet606 [课表数据格式](https://dairoot.github.io/school-api/api/%E8%AF%BE%E8%A1%A8%E6%8E%A5%E5%8F%A3.html)

**Comment by onionnet606** [comment]
@dairoot  十分感谢，已经拿到了
